<footer>
    <a href="index.php?page=index"><img src="./public/medias/img/logoDW.png" alt="logo GAMESQUAD"></a>
    <ul>
        <li><a href="index.php?page=index&action=contact">CONTACT</a></li>
        <li><a href="">F.A.Q</a></li>
        <li><a href="">PROTECTION DE LA VIE PRIVÉE</a></li>
    </ul>
    <div class="reseaux">
        <h3>NOS RÉSEAUX : </h3>
        <ul>
            <li><a href=""><i class="fa-brands fa-square-facebook"></i></a></li>
            <li><a href=""><i class="fa-brands fa-square-instagram"></i></i></a></li>
            <li><a href=""><i class="fa-brands fa-square-twitter"></i></a></li>
        </ul>
    </div>
</footer>
<script src="public/scripts/script.js"></script>
<script src="public/scripts/scriptNavbar.js"></script>

