

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="public/styles/style.css">
    <link rel="stylesheet" href="public/styles/styleFooter.css">
    <link rel="stylesheet" href="public/styles/styleNavbar.css">
    <script src="https://kit.fontawesome.com/785991d3ec.js" crossorigin="anonymous"></script>
    <title>GameSquad</title>
