<?php
ini_set('display_errors', 'on');
require_once 'includes/core/globals.php';
?>
<!doctype html>
<html lang="en">
<head>
    <?php
    require_once 'includes/partials/page_head.phtml';
    ?>
</head>
<body class="bodyCon">
<header>
    <?php
    require_once 'includes/partials/navbar.phtml';
    ?>
</header>
<main>

        <form class="formContact" action="" method="POST">
            <h3>MODIFIER MON PROFIL </h3>

            <div class="nom">
                <label for="name">Nom</label>
                <input type="text" name="name" id="name" value="<?= $user->getName(); ?>">
            </div>
            <div class="prenom">
                <label for="firstname">Prénom</label>
                <input type="text" name="firstname" id="firstname" value="<?= $user->getFirstname(); ?>">
            </div>
            <div class="mail">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" value="<?= $user->getEmail(); ?>">
            </div>
            <div class="pseudo">
                <label for="pseudo">Pseudo</label>
                <input type="text" name="pseudo" id="pseudo" value="<?= $user->getPseudo(); ?>">
            </div>

            <input type="submit" value="Enregistrer">

        </form>






</main>
    <?php
    require_once 'includes/partials/footerUser.phtml';
    ?>
</body>
</html>