<?php
ini_set('display_errors', 'on');
require_once 'includes/core/globals.php';
?>
<!doctype html>
<html lang="en">
<head>
    <?php
require 'includes/partials/page_head.phtml';
?>
</head>
<body class="bodyCon">
<header>
    <?php
    require_once 'includes/partials/navbar.phtml';
    ?>
</header>
<main>
    <div class="cardsContainer">
    <?php
    // on affiche les sessions proposées par l'utilisateur connecté
    $user = $_SESSION['user'];
    //on recupere l'id de l'utilisateur connecté
    $id = $user->getId();
    //on recupere les sessions de l'utilisateur connecté
    $lesSessions = getSessionsByUser($id);



    foreach ($lesSessions as $uneSession) {

        $unJeu = getJeuById($uneSession->getIdjeu());
        $unePlateforme = getPlateformeById($uneSession->getIdplateforme());
        $unUtilisateur = getUtilisateurById($uneSession->getHote()->getId());
        $idAvatar = $unUtilisateur->getIdAvatar();
        $unAvatar = getAvatarById($idAvatar);
        $pathAvatar = $unAvatar->getPath();


        echo '<div class="cardSession">';
        echo '<div class="containerSession left">';
        echo '<div class="user">';
        echo '<img src=' . $pathAvatar . '  </div>';
        echo '</div>';
        echo '<div class="pseudoJoueur">';
        echo '<p>' . $uneSession->getHote()->getPseudo() . '</p>';
        echo '</div>';
        echo '</div>';
        echo '<div class="containerSession">';
        echo '<div class="presentationSession">';
        echo '<h4>' . $uneSession->getTitre() . '</h4>';
        echo '<p>' . $uneSession->getDescription() . '</p>';
        echo '</div>';
        echo '<div class="jeuSession">';
        echo '<p>' . $unJeu. '</p>';
        echo '<p>' . $unePlateforme . '</p>';
        echo '</div>';
        echo '</div>';
        echo '<div class="containerSession right">';
        echo '<div class="dateSession">';
        echo '<p>' . date_format(date_create($uneSession->getDateDebut()), 'd/m/Y') . '</p>';
        echo '<p>' . $uneSession->getHeureDebut() . '</p>';
        echo '</div>';
        echo '<div class="nbJoueur">';
        echo '<p> 1/ ' . $uneSession->getNbJoueur() . '</p>';
        echo '<ul>';
    echo '<li class="btn btn-primary"><a href="index.php?page=session&action=update&id=' .  $uneSession->getId() . '">Modifier</a></li>';
        echo '<li class="btn btn-primary"><a href="index.php?page=session&action=delete&id=' .  $uneSession->getId() . '">Supprimer</a></li>';
        echo '</ul>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
    }
    require_once 'includes/core/models/class/Session.php';
    //on recupere l'id de la session
    ?>
    </div>


</main>

    <?php
    require_once 'includes/partials/footerUser.phtml';
    ?>
</body>
</html>
