<?php
ini_set('display_errors', 'on');
require_once 'includes/core/globals.php';
?>
<!doctype html>
<html lang="en">
<head>
    <?php
require 'includes/partials/page_head.phtml';
?>
</head>
<body class="bodyCon">
<header>
    <?php
    require_once 'includes/partials/navbar.phtml';
    ?>
</header>
<main>

</main>
    <?php
    require_once 'includes/partials/footerUser.phtml';
    ?>
</body>
</html>