<?php
ini_set('display_errors', 'on');
require_once 'includes/core/globals.php';
?>
<!doctype html>
<html lang="en">
<head>
    <?php
require 'includes/partials/page_head.phtml';
?>
</head>
<body class="bodyCon">
<header>
    <?php
    require_once 'includes/partials/navbar.phtml';
    ?>
</header>
<main>
    <div class="cardsContainer">
        <?php
        // on affiche les sessions proposées par tous les utilisateurs
        $lesSessions = getAllSessions();

        foreach ($lesSessions as $uneSession) {
            //$unAvatar = getAvatarById($uneSession->getUtilisateur()->getId());
            $unJeu = getJeuById($uneSession->getIdjeu());
            $unePlateforme = getPlateformeById($uneSession->getIdplateforme());
            $unUtilisateur = getUtilisateurById($uneSession->getHote()->getId());
            $idAvatar = $unUtilisateur->getIdAvatar();
            $unAvatar = getAvatarById($idAvatar);
            $pathAvatar = $unAvatar->getPath();

            echo '<div class="cardSession">';
            echo '<div class="containerSession left">';
            echo '<div class="user">';
            echo '<img src=' . $pathAvatar . '  </div>';
            echo '</div>';
            echo '<div class="pseudoJoueur">';
            echo '<p>' . $uneSession->getHote()->getPseudo() . '</p>';
            echo '</div>';
            echo '</div>';
            echo '<div class="containerSession">';
            echo '<div class="presentationSession">';
            echo '<h4>' . $uneSession->getTitre() . '</h4>';
            echo '<p>' . $uneSession->getDescription() . '</p>';
            echo '</div>';
            echo '<div class="jeuSession">';
            echo '<p>' . $unJeu. '</p>';
            echo '<p>' . $unePlateforme . '</p>';
            echo '</div>';
            echo '</div>';
            echo '<div class="containerSession right">';
            echo '<div class="dateSession">';
            echo '<p>' . date_format(date_create($uneSession->getDateDebut()), 'd/m/Y') . '</p>';
            echo '<p>' . $uneSession->getHeureDebut() . '</p>';
            echo '</div>';
            echo '<div class="nbJoueur">';
            echo '<p> 1/ ' . $uneSession->getNbJoueur() . '</p>';
            if (isset($_SESSION['user']) && $uneSession->getHote()->getId() == $_SESSION['user']->getId()) {
                echo '<a href="index.php?page=session&action=update&id=' . $uneSession->getId() . '"><button class="btn btn-primary">Modifier</button></a>';
            } else {
                echo '<button class="btn btn-primary">Rejoindre</button>';
            }
            echo '</div>';
            echo '</div>';
            echo '</div>';
        }
        ?>
    </div>






</main>

    <?php
    require_once 'includes/partials/footerUser.phtml';
    ?>
</body>
</html>
